Nijelu/The_Duck_Project

.gitignore
app/assets/stylesheets/components/_alert.scss
app/assets/stylesheets/components/_avatar.scss
app/assets/stylesheets/components/_banner.scss
app/assets/stylesheets/components/_button.scss
app/assets/stylesheets/components/_card.scss
app/assets/stylesheets/components/_footer.scss
app/assets/stylesheets/components/_index.scss
app/views/components/_avatar.html.erb
app/views/components/_banner.html.erb
app/views/components/_button.html.erb
app/views/components/_card.html.erb
app/views/components/_footer.html.erb
app/views/components/_navbar.html.erb

Merci de bien vouloir corriger mon travail ;)

components_added

---

Gemfile
Gemfile.lock
app/models/user.rb
app/views/devise/confirmations/new.html.erb
app/views/devise/mailer/confirmation_instructions.html.erb
app/views/devise/mailer/email_changed.html.erb
app/views/devise/mailer/password_change.html.erb
app/views/devise/mailer/reset_password_instructions.html.erb
app/views/devise/mailer/unlock_instructions.html.erb
app/views/devise/passwords/edit.html.erb
app/views/devise/passwords/new.html.erb
app/views/devise/registrations/edit.html.erb
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb
app/views/devise/shared/_links.html.erb
app/views/devise/unlocks/new.html.erb
app/views/layouts/application.html.erb
app/views/shared/_flashes.html.erb
config/environments/development.rb
config/initializers/devise.rb
config/locales/devise.en.yml
config/routes.rb
db/migrate/20180821080258_devise_create_users.rb
db/schema.rb
test/models/user_test.rb

Installation of Devise with creation of the devise model User
Creation of the partial _flashes for the notice and alert of devise
render the partial before the yield in application.html.erb

Add devise

---

app/models/booking.rb
app/models/duck.rb
db/migrate/20180821085118_create_ducks.rb
db/migrate/20180821085719_create_bookings.rb
db/migrate/20180821085807_add_attributes_to_users.rb
db/schema.rb
test/models/booking_test.rb
test/models/duck_test.rb

please please, i want a kind pull request
add all models

model created

---

app/controllers/application_controller.rb
app/controllers/bookings_controller.rb
app/controllers/ducks_controller.rb
app/controllers/users_controller.rb
app/views/bookings/new.html.erb
app/views/bookings/show.html.erb
app/views/ducks/edit.html.erb
app/views/ducks/index.html.erb
app/views/ducks/new.html.erb
app/views/ducks/show.html.erb
app/views/users/edit.html.erb
app/views/users/new.html.erb
app/views/users/show.html.erb
config/routes.rb
test/controllers/bookings_controller_test.rb
test/controllers/ducks_controller_test.rb
test/controllers/users_controller_test.rb

controller_and_routes_generated/device_users_configured

---

.gitignore
Gemfile
Gemfile.lock
app/models/user.rb
app/uploaders/photo_uploader.rb
app/views/devise/registrations/edit.html.erb
app/views/devise/registrations/new.html.erb

it's ok guys just need your validation @GonzagueGru

cloudinary_setted_up

---

app/models/booking.rb
app/models/duck.rb
app/models/user.rb

Associations and basic validations done
TODO : Set the format validation for address, lat, lng, country .....

Associations and Validations done

---

app/views/components/_navbar.html.erb

pour qui veut @Nijelu @ArthurGAUTHIER 
changement de <a> vers link_to

petit correctif pour link_to

---

app/controllers/users_controller.rb
app/policies/user_policy.rb
app/views/users/edit.html.erb
app/views/users/new.html.erb
app/views/users/show.html.erb
test/policies/user_policy_test.rb

Controller pundit done
View dashboard basic done

Dashboard created full MVC - Basic Version

---

Gemfile
Gemfile.lock
app/controllers/ducks_controller.rb
app/models/duck.rb
app/views/components/_duck_form.html.erb
app/views/ducks/new.html.erb

duck_new_form_created

---

app/views/components/_banner.html.erb
app/views/components/_navbar.html.erb
app/views/devise/confirmations/new.html.erb
app/views/devise/passwords/edit.html.erb
app/views/devise/passwords/new.html.erb
app/views/devise/registrations/edit.html.erb
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb
app/views/devise/shared/_links.html.erb
app/views/devise/unlocks/new.html.erb

svp, validez moi
en bref:
- les search renvoient vers index
-log in/ log Out implementé/ Ils ne s'affichent que si on en a besoin (si je suis log in: j'ai pu de bouton log in)
- un chouia de css sur les form devise (container) juste par principe

Modif homepage

---

db/migrate/20180822105155_change_attributes_of_ducks.rb
db/schema.rb

Remove column postal_code / city / country
REname column lat->latitude / lng -> longitude

Duck model simplified and corected

---

Gemfile.lock

Update the gemfile.lock to fix the failed builds on heroku

Updated Gemfile.lock

---

Gemfile.lock
app/controllers/ducks_controller.rb
app/models/duck.rb
app/views/components/_duck_form.html.erb

duck_new_form_finished

---

app/assets/stylesheets/components/_card.scss
app/views/components/_card.html.erb

card basic design done

---

app/javascript/components/autocomplete.js
app/views/components/_navbar.html.erb
app/views/ducks/edit.html.erb
app/views/ducks/new.html.erb

address_autocomplete_implemented/duck_edit_created

---

app/controllers/ducks_controller.rb
app/policies/duck_policy.rb
app/views/users/show.html.erb

add delete link | duck controller done

---

Gemfile
Gemfile.lock
app/models/duck.rb
app/policies/duck_policy.rb
app/views/components/_banner.html.erb
app/views/pages/home.html.erb

Add search functionality with pgsearch

---

app/controllers/ducks_controller.rb
app/policies/duck_policy.rb
app/views/components/_banner.html.erb
app/views/components/_navbar.html.erb

Make search work

---

app/views/users/show.html.erb

set size for images

---

app/assets/stylesheets/config/_bootstrap_variables.scss
app/views/bookings/new.html.erb
app/views/bookings/show.html.erb
app/views/users/show.html.erb

Style 3/4 done
